package package300;

/**
 * Created by jingshanyin on 11/19/16.
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        char sumS = 'a';
        char sumT = 'a';
        int i = 0;
        for (; i < s.length(); i++) {
            sumS += s.charAt(i);
            sumT += t.charAt(i);
        }
        sumT += t.charAt(i);
        return (char)(sumT - sumS);
    }
}
